# application-local.yml
spring:
  config:
    activate:
      on-profile: local
    import: optional:file:.env.properties

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.naver.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    default-encoding: UTF-8

  ai:
    vertex:
      ai:
        credentials-uri: ${GCP_PATH}
        gemini:
          project-id: ${GCP_PROJECT_ID}
          location: ${GCP_REGION}
      gemini:
          chat:
            options:
              model: ${GEMINI_MODEL}
              temperature: 0.7

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

server:
  port: 8080

app:
  magic-link:
    base-url: http://localhost:8080
    enabled: true

#logging:
#  level:
#    com.mumyungdiary.mm_backend.security.jwt: DEBUG
#    org.springframework.security: DEBUG
